# Generated by Django 4.2.27 on 2026-01-11 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCabello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='cortes/', verbose_name='Imagen')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('servicio_domicilio', models.BooleanField(default=False, verbose_name='Servicio a domicilio')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacar en portada')),
            ],
            options={
                'verbose_name': 'Corte de Cabello',
                'verbose_name_plural': 'Cortes de Cabello',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artistico', models.CharField(max_length=100, verbose_name='Nombre Artístico')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('foto_perfil', models.ImageField(upload_to='perfil/', verbose_name='Foto de Perfil')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('spotify', models.URLField(blank=True, verbose_name='Spotify')),
            ],
            options={
                'verbose_name': 'Información Personal',
                'verbose_name_plural': 'Información Personal',
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('respondido', 'Respondido')], default='nuevo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('cancion', 'Canción'), ('album', 'Álbum'), ('video', 'Video Musical')], default='cancion', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('url_spotify', models.URLField(blank=True, verbose_name='URL Spotify')),
                ('url_youtube', models.URLField(blank=True, verbose_name='URL YouTube')),
                ('url_soundcloud', models.URLField(blank=True, verbose_name='URL SoundCloud')),
                ('imagen_portada', models.ImageField(blank=True, upload_to='musica/', verbose_name='Imagen de Portada')),
                ('fecha_lanzamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Lanzamiento')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacar en portada')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Música',
                'ordering': ['-fecha_lanzamiento'],
            },
        ),
    ]
