# Generated by Django 4.2.27 on 2026-01-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='hero/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=1, help_text='Orden de aparición (1, 2 o 3)', verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, help_text='Mostrar esta imagen en el hero', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Imagen Hero',
                'verbose_name_plural': 'Imágenes Hero',
                'ordering': ['orden'],
            },
        ),
    ]
