# Generated by Django 6.0.3 on 2026-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_imagenhero'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionpersonal',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Otras fortalezas/competencias.', verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='exitos',
            field=models.TextField(blank=True, help_text='Lista de éxitos separados por salto de línea.', verbose_name='Éxitos'),
        ),
    ]
