# Generated by Django 4.2.29 on 2026-03-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_informacionpersonal_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionpersonal',
            name='foto_logros',
            field=models.ImageField(blank=True, help_text='Imagen que aparecerá en la sección de Logros del carrusel.', null=True, upload_to='logros/', verbose_name='Foto de Logros'),
        ),
    ]
