# Generated by Django 4.2.29 on 2026-03-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_informacionpersonal_foto_logros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'verbose_name': 'Red de Contacto', 'verbose_name_plural': 'Redes de Contacto'},
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='telefono',
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='instagram',
            field=models.URLField(blank=True, help_text='Ejemplo: https://instagram.com/tu_usuario', null=True, verbose_name='Enlace de Instagram'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Ejemplo: https://wa.me/573001234567', null=True, verbose_name='Enlace de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='email',
            field=models.EmailField(help_text='Tu correo para que te contacten.', max_length=254, verbose_name='Correo Electrónico'),
        ),
    ]
