# Generated by Django 4.2.29 on 2026-03-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_mensajecontacto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='google_maps',
            field=models.URLField(blank=True, help_text='Ve a Google Maps, busca tu ubicación, dale a "Compartir" y pega ese enlace aquí.', null=True, verbose_name='Enlace de Google Maps'),
        ),
    ]
